nome = input('Qual é o seu nome: ')
print('20 espaços => {:20}!'.format(nome))
print('20 espaços align direita => {:>20}!'.format(nome))
print('20 espaços align esquerda => {:>20}!'.format(nome))
print('20 espaços align centro => {:^20}!'.format(nome))
print('20 espaços align centro preechendo => {:*^20}!'.format(nome))
